### ISSUE TITLE
Where can I find the available object names such as "player.state.health" and "data.player.name"?

### ISSUE THREAD

**Issue by watser** [schroffl/cs-gamestate#1]
Not really an "issue", but I didn't know where to post otherwise (please remove if you don't allow of this kind of posts). I hope the title explains itself, thanks!

**Comment by watser** [comment]
Or would the most handy way be to use:

``` javascript
CSGameState.on('<update>', function(data) {
     console.log(data)
});
```

Log all the data and use this?

**Comment by schroffl** [comment]
Yes, this would be pretty much the best way to find out, since Valve's documentation regarding this feature is currently only consisting of [this article](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration) published in their wiki which doesn't even contain much information...

**Comment by watser** [comment]
Thank you :)
