### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by Dieterfu** [schroffl/cs-gamestate#2]
Hello,
can you please add a function which allows checking the auth token which is in the cfg file?

Thank you very much
Regards
Dieter

**Comment by schroffl** [comment]
I will check it out :)

**Comment by Dieterfu** [comment]
Thanks a lot

**Comment by schroffl** [comment]
The quickest and easiest solution would probably be something like this:
```javascript
gamestateInstance.on('<authentication>', (auth, cb) => {
  if(auth.token === 'my_simple_token')
    cb(true);
  else
    cb(false);
});
```

I might rewrite the API anyways at some point, but if this rather dirty solution is okay for you I can implement it right now.

**Comment by Dieterfu** [comment]
Would be good. Thanks a lot.

Regards
Dieter

**Comment by schroffl** [comment]
I just noticed that the auth data should already be included in any request.

```json
{
  "provider": {
    "name": "Counter-Strike: Global Offensive",
    "appid": 730,
    "version": 13606,
    "steamid": "12345678901234567",
    "timestamp": 1507918040
  },
  "player": {
    "steamid": "12345678901234567",
    "name": "schroffl",
    "activity": "menu"
  },
  "auth": {
    "token": "CCWJu64ZV3JHDT8hZc"
  }
}
```
You could catch that by attaching a listener to the `<update>` event, tough this can't prevent parsing.

---
## Solution with the current version
The only way to completely prevent parsing is to create an http-server yourself which will pass the data to `CSGameState.parse` if the authentication succeeds.

### Example (with express)
```javascript
const http = require('http');
const express = require('express');
const bodyParser = require('body-parser');
const csgs = require('cs-gamestate');

const router = express();
const server = http.createServer();
const gamestate = new csgs({ 'createServer': false }, 3000);

router.use(bodyParser.json());

router.post('/data', (req, res) => {
  if(req.body.auth.token === 'my_simple_token') {
    gamestate.parse(req.body);
    res.status(200).end();
  } else
    res.status(401).end();
});

gamestate.on('player.state.health', (health, oldHealth, data) => {
  console.log(data.player.name, 'has', health, 'HP');
});
```

I'm not sure if this works, because I didn't test it at all, but you probably get the idea.
If anything is wrong or you have a question just let me know :)

**Comment by schroffl** [comment]
I'm going to close this issue for now. If any further questions arise, feel free to ask :)
